package com.example.rubikscubetrainer;

import android.content.Context;
import android.opengl.GLSurfaceView;
import android.util.AttributeSet;
import android.view.MotionEvent;

import com.example.rubikscubetrainer.matrix.MatrixTrackingGL;

import javax.microedition.khronos.opengles.GL;

public class GLView extends GLSurfaceView {
	private GLRenderer glrenderer;
	private float x0 = 0.0f;
	private float y0 = 0.0f;
	private float x1 = 0.0f;
	private float y1 = 0.0f;
	private int mode; //  0 - playing with virtual cube generated by the app
	// 1- playing with scanned cube
	// 2- showing one of the scanned cubes from the db

	public GLView(Context context, AttributeSet attr) {
		super(context, attr);
		if (context.getClass().toString().endsWith("PlayingWithScannedCube"))
			mode = 1;
		else if (context.getClass().toString().endsWith("ScannedCubeFromDB"))
			mode = 2;
		else
			mode = 0;
//		if (context.getClass().toString().endsWith("ScannedCubeFromDB"))

		if (glrenderer != null) return;
		glrenderer = new GLRenderer(getResources().getDisplayMetrics().widthPixels,
				getResources().getDisplayMetrics().heightPixels, context, mode);
		setRenderer(glrenderer);
		setGLWrapper(new GLWrapper() {

			@Override
			public GL wrap(GL gl) {
				return new MatrixTrackingGL(gl);
			}
		});
	}

	public GLView(Context context) {
		super(context);
		if (context.getClass().toString().endsWith("PlayingWithScannedCube"))
			mode = 1;
		else
			mode = 0;
		if (glrenderer != null) return;
		glrenderer = new GLRenderer(getResources().getDisplayMetrics().widthPixels,
				getResources().getDisplayMetrics().heightPixels, context, mode);
		setRenderer(glrenderer);
		setGLWrapper(new GLWrapper() {

			@Override
			public GL wrap(GL gl) {
				return new MatrixTrackingGL(gl);
			}
		});
	}

	public void mix() {
		glrenderer.mix();
	}

	public void cancelMove() {
		glrenderer.cancelMove();
	}

	public boolean onTouchEvent(final MotionEvent event) {
		glrenderer.handleTouch(event);
		return true;
	}

	public void setMode(int mode) {
		this.mode = mode;
		glrenderer.setMode(mode);
	}

	public GLRenderer getGlrenderer() {
		return glrenderer;
	}
}
